### ISSUE TITLE
Windows 7 compatible!

### ISSUE THREAD

**Issue by sapioit** [inkdropapp/forum#3]
Hi,

I tried the Zip version on Windows 7 and it seems to be working properly. At least as far as I could tell. Maybe add Windows 7 on the list of supported OSes, please?

**Comment by craftzdog** [comment]
This app is built with Electron so the supported platforms are [depended on it](https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md).
I'm glad to hear that Inkdrop works on Windows 7 because I was testing it on Windows 8.1.
I'll add win7 to the list of supported OSes.
Thanks for reporting!

**Comment by sapioit** [comment]
Just so you know, since it's built with electron, Windows 7+ (7 to latest) is compatible (unless something "special"/wierd happens that normally shouldn't). For Windows XP+, there is nw.js, but it's buggy, at the moment, or so I've heared/read.

**Comment by craftzdog** [comment]
Yeah, thank you for letting me know 😄 
Now win7+ is displayed as supported platform.
