### ISSUE TITLE
Feature request: Ability to lock app, or auto logout

### ISSUE THREAD

**Issue by ghacct22** [inkdropapp/forum#36]
## Feature request
Inkdrop has security/privacy features like encryption and the ability to use your own database, but remains logged in and decrypted whenever the computer unlocks or reboots. I would like the option to have Inkdrop log me out and require my username and password when the computer or the application restarts. Even the ability to lock the app behind a pin would work, so long as Inkdrop doesn't assume that i want anyone who uses my computer to also have full access to my notes.

### Info
- Platform: macOS and Windows
- Platform version: Sierra and 10
- App Version: 3.3.4

**Comment by craftzdog** [comment]
Thanks for the feedback!
If a person could use your computer with your account, he/she also can access to keychains.
I recommend you to let other person log in with his/her own account.
You should log out or lock your computer itself whenever you leave.

**Comment by ghacct22** [comment]
How about a logout command in the hotkeys section, right now it looks like it doesn't exist. The current setup is inconvenient for people who share computers.

**Comment by craftzdog** [comment]
How do you manage your email apps and web browsers?
They don't have the locking feature, too.
I don't get your use case.

**Comment by craftzdog** [comment]
I could add a keymap for the logout command but I'm worrying about your security policy.
Again, I recommend you to have accounts for each people who share your computer.

**Comment by ghacct22** [comment]
I agree that my personal computer security policy could be improved by having separate user accounts. I got the idea from my password manager, Dashlane, which has different login methods to improve security like two factor authentication, and configurability over how long the app remains logged in. The use cases between the two products is vastly different, and perhaps it is just a case of security theater, but in recent years there has been a lot of concern about unauthorized computer access and it would be nice to think that if, for some reason, someone had access to my machine that they didn't also immediately have access to all of my content in Inkdrop as well.

This concern is doubled for the mobile app, which i haven't had the opportunity to try yet since i'm on android, because of recent policies of demanding access to someone's phone. If my phone is being examined by border security, for example, it would be nice if more sensitive content were still secured.

This is more of a personal preference/wish list idea and by no means an essential feature, but i wanted to adequately explain my reasoning since it seems like we weren't on the same page.

**Comment by craftzdog** [comment]
Your concern about cracking is right.
Protecting from cracker's access and sharing computer with friends/family are related but different problem.

If you worry about cracking seriously, please stop sharing computer with same user account immediately because other people may potentially make a security hole. Separating user account means that your files are protected with permissions.

Security is of course important and I'm always thinking how to make it more secure.
There is trade-off between security, usability and performance.
So it has to be carefully considered how to protect data in many way.
At the moment, I don't recommend you to store sensitive data like passwords to Inkdrop.

Auto log-out feature is nice to have but not for everyone.
I want to keep Inkdrop simple.
I'd say no for now, same for the mobile app.

So anyway, I added `application:logout` command in v3.4.2. You can configure a keymap in `keymap.cson` file as following:

```
'body':
  'shift-alt-cmd-o': 'application:logout'
```

You can log out quickly with this keymap.
Thanks for the suggestion!
