### ISSUE TITLE
Note link opens note instead of just copying

### ISSUE THREAD

**Issue by ghacct22** [inkdropapp/forum#39]
## Bug report
Right clicking on another note to `Copy Note Link` opens the note in the main viewer, meaning you have to go find the note you wanted to put the link into again. There is, however, a back button, which should be helpful. There is also no hotkey to copy a note link. 

### Info
- Platform: macOS
- Platform version: Sierra
- App Version: 3.3.4

### Reproduce
Right click a note in the side bar and select Copy Note Link

### Expected Outcome
The note link is copied

### Actual Outcome
The note link is copied and the active note switches to the note you are trying to copy

**Comment by craftzdog** [comment]
Hi,

Currently right-click selects the target note but the UI is delayed to display the selection due to blocking UI thread by the context menu.
It seems to be not useful and confusing.
I got another feature request which adds an ability to handle multiple notes with context menu, and it's related to this issue.

I'll look into it. Thanks!

**Comment by craftzdog** [comment]
Refined the context menu behaviors in v3.6.0.
Thank you!
