### ISSUE TITLE
Viewing images in Edit mode

### ISSUE THREAD

**Issue by tdharris** [inkdropapp/forum#52]
As a user, I'd like to stay in `Edit` mode and be able to view images without having to toggle the `View` or `Side-by-Side` mode. Seeing the image is more important to me than the inkdrop url to the image; however, keeping both would be a good balance where the image is rendered beneath the markdown tag.

![image](https://user-images.githubusercontent.com/5355939/27919954-5ccbebfc-6230-11e7-861a-0b3d9e185b35.png)
![image](https://user-images.githubusercontent.com/5355939/27919965-6620f2ba-6230-11e7-80f8-9d47f94e5017.png)

From a markdown-purist perspective, I understand this enhancement doesn't make much sense, but I think it does after considering what markdown is being used here for, as I don't think it's **just** for generating HTML. Rendering the image in the `Edit` view makes sense here, in a note-taking app where users frequently edit. When a user prefers `Edit` mode (look & feel and ability to edit the note), they should be permitted to have the image rendered also. I am regularly modifying / improving my notes and would prefer to stay in `Edit` mode while still seeing images.

**Comment by craftzdog** [comment]
Hi, thanks for the suggestion.

This is...a neat idea.
I've ever thought it's annoying to toggle the view mode often to check images. So it makes sense for me.
I think you are right because I guess why people love Markdown is that its formatting is similar to what it will look like after converted to HTML.
But since it's the plain text format, it can't show images as it is.
Most Markdown editors don't support inline image widget as far as I know, so it would be a big advantage for Inkdrop if supported.

The editor is built with CodeMirror which supports [the inline widget](https://codemirror.net/demo/widget.html).
Following image is just a proof of concept that shows the image underneath the URI:

![screen shot 2017-07-07 at 11 03 40](https://user-images.githubusercontent.com/1332805/27940159-04769734-6304-11e7-8724-19094c71acfc.png)

It would be great to add an option for it.
I will plan to support it. Maybe next month.
Thank you again for the great suggestion!

**Comment by craftzdog** [comment]
Supported in v3.7.0. Thanks again for your suggestion!
https://medium.com/@inkdrop/new-feature-inline-image-widgets-v3-7-0-ee919436623f
