### ISSUE TITLE
Make `editor:find*` and `editor:replace` commands global

### ISSUE THREAD

**Issue by wapa5pow** [inkdropapp/forum#57]
## Bug report
The following is the description.

<img width="1018" alt="inkdrop" src="https://user-images.githubusercontent.com/5561944/28096063-18ab78ba-66e1-11e7-935f-d5c2316b9fed.png">

### Info
- Platform: (macOS)
- Platform version: (Sierra 10.12.5)
- App Version: (3.6.1)

**Comment by craftzdog** [comment]
Hi, thank you for the report!

Yeah it's definitely useful for exploring notes!
Currently following commands/keybindings only work if the focus is on the editor:

 * `editor:find`
 * `editor:find-next`
 * `editor:find-prev`
 * `editor:replace`

But I would make them global so that you can search within a note even if you are at a search bar!

**Comment by wapa5pow** [comment]
That would be great. Thx! I'm using Dash snippets for note purpose. If the issue's function is implemented, the search future is similar to Dash so that I can move to Inkdrop.

**Comment by craftzdog** [comment]
Supported in v3.7.1.
Thanks for the suggestion!

**Comment by wapa5pow** [comment]
Thx! Great! you are very quick.
