### ISSUE TITLE
Attachment Support

### ISSUE THREAD

**Issue by kelchm** [inkdropapp/forum#61]
It would be great for Inkdrop to support arbitrary attachments in addition to images.

**Comment by craftzdog** [comment]
Hi, thank you for the suggestion.

Yeah it would be nice to have but I'm afraid to say no for supporting attachment because this app is for developers primarily.
I assume that the attachment is going to be PDF, ZIP, DOCX and XLSX files but it's usually not necessary for note-taking regarding programming.
Instead, Markdown supports links, so you can add a link to a file uploaded on a cloud service.

The attachment feature would make the app complicated by such as previewing, syncing large files and encryption/decryption. It would cause the app to be buggy and unstable.
I would like to focus on keeping the app simple and clean and not to over-complicate things (like basically all the other note-taking systems out there).
