### ISSUE TITLE
Vim mode plugin or help on creating one

### ISSUE THREAD

**Issue by czcollier** [inkdropapp/forum#76]
## Feature Request
Seems like a vim mode would be not too hard, given CodeMirror has one.  I tried creating a plugin that would toggle the CodeMirror vim mode.  I could get to the CodeMirror instance and manipulate it, but for CodeMirror vim mode to work, one needs to import their 'keymap/vim.js' file, which I couldn't figure out how to do in the Inkdrop plugin environment.

I'd love either a vim mode plugin or some direction on how I could implement one.

Thanks!

**Comment by craftzdog** [comment]
Hi,

That's great to know you are trying to make a vim mode plugin!
I'm happy to help you.
Yes, it's easy to do as you said.
Actually Inkdrop bundles keymap files of CodeMirror so you can import it like so:

```javascript
require('codemirror/keymap/vim')
```

But there's a problem that it doesn't work to add vim bindings to Inkdrop's CodeMirror instance since Inkdrop's one is loaded from the bundled main script, not from `node_modules/codemirror`.
I think it is possible to load it from `node_modules` so that we can use keymap extensions.
I will release fixed version soon!

And you can enable vim keymap as following:

```javascript
var cm = inkdrop.getActiveEditor().codeMirror
cm.setOption('keyMap', 'vim')
```

I noticed that when the vim mode enabled it conflicts default keybindings of the editor such as `editor:new-line` so these keybindings need to be overridden.

**Comment by timsuchanek** [comment]
I would love to see this landing in Inkdrop!

**Comment by craftzdog** [comment]
Sure thing! I'd like to include vim support to the next roadmap. Thanks for the comment.

**Comment by craftzdog** [comment]
This topic has been moved to the new forum: https://forum.inkdrop.info/t/vim-mode-plugin/56

**Comment by craftzdog** [comment]
Finally available!

https://app.inkdrop.info/plugins/vim

Thanks for the suggestion.
